In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
class Net(nn.Module):
    def __init__(self, input_dim, num_classes):
      super().__init__()
      self.linear = nn.Linear(input_dim, num_classes)
      print(input_dim)
      self.linear2 = nn.Linear(input_dim, num_classes)
      self.sigmoid = nn.Sigmoid()

    def forward(self, input):
      print(input)
      k = self.linear(input)
      print(k)
      l = self.linear2(k)
      return self.sigmoid(l)
      # return self.sigmoid(self.linear(self.linear(input)))

model = Net(2, 2)
x = torch.Tensor([1,2])
model(x)

2
tensor([1., 2.])
tensor([0.0056, 0.9788], grad_fn=<AddBackward0>)


tensor([0.3999, 0.7297], grad_fn=<SigmoidBackward0>)